language: node_js
node_js:
- "8.11.0"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
- npm install mocha -g
script:
- mocha test